# Generated by Django 3.0.4 on 2020-03-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemIdCol', models.CharField(max_length=100)),
                ('itemNameCol', models.CharField(max_length=100)),
                ('itemDecCol', models.CharField(max_length=300)),
                ('itemTextCol', models.CharField(max_length=2000)),
                ('itemImageCol', models.IntegerField()),
                ('itemPriceCol', models.IntegerField()),
                ('itemSellCol', models.IntegerField()),
            ],
        ),
    ]
