# Generated by Django 3.0.4 on 2020-03-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionsTb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCol', models.CharField(max_length=100)),
                ('nameCol', models.CharField(max_length=100)),
                ('titleCol', models.CharField(max_length=300)),
                ('blurbCol', models.CharField(max_length=2000)),
                ('attackCol', models.IntegerField()),
                ('defenseCol', models.IntegerField()),
                ('magicCol', models.IntegerField()),
                ('difficultyCol', models.IntegerField()),
                ('imageCol', models.CharField(max_length=200)),
                ('hpCol', models.FloatField()),
                ('movespeedCol', models.FloatField()),
                ('armorCol', models.FloatField()),
                ('attackrangeCol', models.FloatField()),
                ('hpregenCol', models.FloatField()),
                ('attackdamageCol', models.FloatField()),
                ('attackspeedCol', models.FloatField()),
            ],
        ),
    ]
