# Generated by Django 3.0.4 on 2020-05-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championstb',
            name='attackdamageCol',
            field=models.FloatField(max_length=4),
        ),
        migrations.AlterField(
            model_name='championstb',
            name='blurbCol',
            field=models.CharField(max_length=250),
        ),
    ]
