# Generated by Django 3.0.4 on 2020-05-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0002_auto_20200510_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championstb',
            name='attackdamageCol',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='championstb',
            name='attackrangeCol',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='championstb',
            name='hpCol',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
